# Generated by Django 4.0 on 2021-12-20 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='examdb',
            fields=[
                ('ExamId', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('ExamName', models.CharField(max_length=20, verbose_name='Exam Name')),
                ('ExamType', models.CharField(max_length=25, verbose_name='Exam Type')),
                ('ExamYear', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1900)], verbose_name='Exam Year')),
                ('ExamDuration', models.CharField(max_length=20, verbose_name='Exam Duration')),
                ('ExamDate', models.DateField(verbose_name='Exam Date')),
                ('IsActive', models.BooleanField(default=1)),
            ],
        ),
    ]
